/*
  Copyright 2022 Adobe. All rights reserved.
  This file is licensed to you under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License. You may obtain a copy
  of the License at http://www.apache.org/licenses/LICENSE-2.0
  Unless required by applicable law or agreed to in writing, software distributed under
  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
  OF ANY KIND, either express or implied. See the License for the specific language
  governing permissions and limitations under the License.
*/

package com.adobe.marketing.mobile.edge.bridge;

import static com.adobe.marketing.mobile.edge.bridge.EdgeBridgeConstants.LOG_TAG;

import com.adobe.marketing.mobile.Event;
import com.adobe.marketing.mobile.EventSource;
import com.adobe.marketing.mobile.EventType;
import com.adobe.marketing.mobile.Extension;
import com.adobe.marketing.mobile.ExtensionApi;
import com.adobe.marketing.mobile.services.Log;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.TimeZone;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

class EdgeBridgeExtension extends Extension {

	private static final String CLASS_NAME = "EdgeBridgeExtension";
	private ExecutorService executorService;
	private final Object executorMutex = new Object();

	private static final SimpleDateFormat iso8601DateFormat;

	static {
		final Locale posixLocale = new Locale(Locale.US.getLanguage(), Locale.US.getCountry(), "POSIX");
		iso8601DateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", posixLocale);
		iso8601DateFormat.setTimeZone(TimeZone.getTimeZone("GMT"));
	}

	protected EdgeBridgeExtension(final ExtensionApi extensionApi) {
		super(extensionApi);
		//		ExtensionErrorCallback<ExtensionError> listenerErrorCallback = new ExtensionErrorCallback<ExtensionError>() {
		//			@Override
		//			public void error(final ExtensionError extensionError) {
		//				Log.error(
		//					EdgeBridgeConstants.LOG_TAG,
		//					CLASS_NAME,
		//					"%s - Failed to register listener: %s", CLASS_NAME, extensionError.getErrorName()
		//				);
		//			}
		//		};
		//
		//		extensionApi.registerEventListener(
		//			EdgeBridgeConstants.EventType.GENERIC_TRACK,
		//			EdgeBridgeConstants.EventSource.REQUEST_CONTENT,
		//			ListenerGenericTrackRequestContent.class,
		//			listenerErrorCallback
		//		);
		//
		//		extensionApi.registerEventListener(
		//			EdgeBridgeConstants.EventType.RULES_ENGINE,
		//			EdgeBridgeConstants.EventSource.RESPONSE_CONTENT,
		//			ListenerRulesEngineResponseContent.class,
		//			listenerErrorCallback
		//		);
	}

	@Override
	protected String getName() {
		return EdgeBridgeConstants.EXTENSION_NAME;
	}

	@Override
	protected String getVersion() {
		return EdgeBridgeConstants.EXTENSION_VERSION;
	}

	@Override
	protected void onRegistered() {
		getApi().registerEventListener(EventType.GENERIC_TRACK, EventSource.REQUEST_CONTENT, this::handleTrackRequest);
		getApi()
			.registerEventListener(
				EventType.RULES_ENGINE,
				EventSource.RESPONSE_CONTENT,
				this::handleRulesEngineResponse
			);
	}

	/**
	 * Called by listeners to retrieve an {@code ExecutorService}.
	 * The {@code ExecutorService} is used to process events on a separate thread than the
	 * {@code EventHub} thread on which they were received. Processing events on a separate
	 * thread prevents blocking of the {@code EventHub}.
	 *
	 * @return this extension's instance of a single thread executor
	 */
	ExecutorService getExecutor() {
		synchronized (executorMutex) {
			if (executorService == null) {
				executorService = Executors.newSingleThreadExecutor();
			}

			return executorService;
		}
	}

	/**
	 * Handles generic Analytics track events coming from the public APIs.
	 * @param event the generic track request event
	 */
	void handleTrackRequest(final Event event) {
		if (event == null) {
			Log.trace(LOG_TAG, CLASS_NAME, "%s - Unable to handle track request as event is null.", CLASS_NAME);
			return;
		}

		final Map<String, Object> eventData = event.getEventData();

		if (isNullOrEmpty(eventData)) {
			Log.trace(
				LOG_TAG,
				CLASS_NAME,
				"%s - Unable to handle track request event with id '%s': event data is missing or empty.",
				CLASS_NAME,
				event.getUniqueIdentifier()
			);
			return;
		}

		dispatchTrackRequest(eventData, event.getTimestamp());
	}

	/**
	 * Handles Analytics track events generated by a rule consequence.
	 * @param event the rules engine response event
	 */
	void handleRulesEngineResponse(final Event event) {
		if (event == null) {
			Log.trace(LOG_TAG, CLASS_NAME, "%s - Ignoring Rules Engine response event as event is null.", CLASS_NAME);
			return;
		}

		final Map<String, Object> eventData = event.getEventData();

		if (isNullOrEmpty(eventData)) {
			Log.trace(
				LOG_TAG,
				CLASS_NAME,
				"%s - Ignoring Rules Engine response event with id '%s': event data is missing or empty.",
				CLASS_NAME,
				event.getUniqueIdentifier()
			);
			return;
		}

		try {
			@SuppressWarnings("unchecked")
			final Map<String, Object> consequence = (Map<String, Object>) eventData.get("triggeredconsequence");

			if (isNullOrEmpty(consequence)) {
				Log.trace(
					LOG_TAG,
					CLASS_NAME,
					"%s - Ignoring Rule Engine response event with id '%s': consequence data is missing or empty.",
					CLASS_NAME,
					event.getUniqueIdentifier()
				);
				return;
			}

			final String type = (String) consequence.get("type");

			if (!"an".equals(type)) {
				// Not an Analytics rules consequence
				return;
			}

			final String id = (String) consequence.get("id");

			if (isNullOrEmpty(id)) {
				Log.trace(
					LOG_TAG,
					CLASS_NAME,
					"%s - Ignoring Rule Engine response event with id '%s': consequence id is missing or empty.",
					CLASS_NAME,
					event.getUniqueIdentifier()
				);
				return;
			}

			@SuppressWarnings("unchecked")
			final Map<String, Object> detail = (Map<String, Object>) consequence.get("detail");

			if (isNullOrEmpty(detail)) {
				Log.trace(
					LOG_TAG,
					CLASS_NAME,
					"%s - Ignoring Rule Engine response event with id '%s': consequence detail is missing or empty.",
					CLASS_NAME,
					event.getUniqueIdentifier()
				);
				return;
			}

			dispatchTrackRequest(detail, event.getTimestamp());
		} catch (ClassCastException e) {
			Log.debug(
				EdgeBridgeConstants.LOG_TAG,
				CLASS_NAME,
				"%s - Failed to parse Rules Engine response event with id '%s': %s",
				CLASS_NAME,
				event.getUniqueIdentifier(),
				e.getLocalizedMessage()
			);
		}
	}

	/**
	 * Helper to create and dispatch an experience event.
	 * @param data map containing free-form data to send to Edge Network
	 * @param timestamp timestamp of Event
	 */
	private void dispatchTrackRequest(final Map<String, Object> data, final long timestamp) {
		Map<String, Object> xdmData = new HashMap<>();
		xdmData.put("eventType", EdgeBridgeConstants.JsonValues.EVENT_TYPE);
		xdmData.put("timestamp", iso8601DateFormat.format(new Date(timestamp)));

		Map<String, Object> eventData = new HashMap<>();
		eventData.put("xdm", xdmData);
		eventData.put("data", data);

		final Event event = new Event.Builder(
			EdgeBridgeConstants.EventNames.EDGE_BRIDGE_REQUEST,
			EdgeBridgeConstants.EventType.EDGE,
			EventSource.REQUEST_CONTENT
		)
			.setEventData(eventData)
			.build();

		//		MobileCore.dispatchEvent(
		//			event,
		//			new ExtensionErrorCallback<ExtensionError>() {
		//				@Override
		//				public void error(ExtensionError extensionError) {
		//					Log.debug(
		//						EdgeBridgeConstants.LOG_TAG,
		//						CLASS_NAME,
		//						"%s - Failed to dispatch Edge Bridge request event with id '%s': %s", CLASS_NAME, event.getUniqueIdentifier(), extensionError != null ? extensionError.getErrorName() : "unexpected"
		//					);
		//				}
		//			}
		//		);
		getApi().dispatch(event);
	}

	private boolean isNullOrEmpty(final String str) {
		return str == null || str.isEmpty();
	}

	private boolean isNullOrEmpty(final Map map) {
		return map == null || map.isEmpty();
	}
}
