version: 2.1
orbs:
  android: circleci/android@1.0

# Workflows orchestrate a set of jobs to be run;
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - validate-code
      - build-and-unit-test:
          requires:
            - validate-code
      - functional-test:
          requires:
            - validate-code
 
jobs:
  validate-code:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - run:
          name: Check Code Format
          command: make format-check

  build-and-unit-test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - run:
          name: Javadoc
          command: make ci-javadoc
      - store_artifacts:
          path: ci/javadoc/build/reports

      - run:
          name: Build
          command: make ci-build

      - run:
          name: Build App
          command: make ci-build-app

      - run:
          name: UnitTests
          command: make ci-unit-test

      # code coverage
      - run:
          name: Upload Code Coverage Report
          command: |
            curl -s https://codecov.io/bash > codecov;
            VERSION=$(grep 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
            SHAVERSION=$(shasum -v);
            echo "Using CodeCov version '$VERSION'"
            echo "Using shasum '$SHAVERSION'"
            for i in 1 256 512
            do
              shasum -a $i -c --ignore-missing <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM") ||
              shasum -a $i -c <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM" | grep -w "codecov")
            done
            bash ./codecov -v -X s3 -c -D "./ci/unit-test/build/reports" -F unit-tests

      - store_artifacts:
          path: ci/unit-test/build/reports

      - store_test_results:
          path: ci/unit-test/build/test-results

  functional-test:
    executor:
      name: android/android-machine
      resource-class: large
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          #   It should match the name seen in the "sdkmanager --list" output
          system-image: system-images;android-29;default;x86
          #   The command to be run, while waiting for emulator startup
          post-emulator-launch-assemble-command: make ci-build
          #   The test command
          test-command: make ci-functional-test
      
      # code coverage
      - run:
          name: Upload Code Coverage Report
          command: |
            curl -s https://codecov.io/bash > codecov;
            VERSION=$(grep 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
            SHAVERSION=$(shasum -v);
            echo "Using CodeCov version '$VERSION'"
            echo "Using shasum '$SHAVERSION'"
            for i in 1 256 512
            do
              shasum -a $i -c --ignore-missing <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM") ||
              shasum -a $i -c <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM" | grep -w "codecov")
            done
            bash ./codecov -v -X s3 -c -D "./ci/functional-test/build/reports" -F functional-tests

      - store_artifacts:
          path: ci/functional-test/build/reports

      - store_test_results:
          path: ci/functional-test/build/outputs/androidTest-results
          
    
