version: 2.1
orbs:
  # Use the circleci android orb version that supports OpenJDK17 required by AGP 8.2+
  android: circleci/android@2.4.0
  codecov: codecov/codecov@4.0.1

# Workflows orchestrate a set of jobs to be run;
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - validate-code
      - build-and-unit-test:
          requires:
            - validate-code
      - functional-test:
          requires:
            - validate-code
 
jobs:
  validate-code:
    executor:
      name: android/android-docker
      resource-class: medium
      tag: 2024.01.1-node
    steps:
      - checkout

      - android/restore-gradle-cache

      - android/restore-build-cache

      # TODO: Re-enable these steps once formatting and linting issues are resolved
      # - run:
      #     name: Check Format
      #     command: make checkformat
      
      # - run:
      #     name: Lint
      #     command: make lint
      
      # Store Lint report 
      - store_artifacts:
          path: code/edgebridge/build/reports

      - android/save-gradle-cache

      - android/save-build-cache

  build-and-unit-test:
    executor:
      name: android/android-docker
      resource-class: medium
      tag: 2024.01.1
    steps:
      - checkout

      - android/restore-gradle-cache

      - android/restore-build-cache

      - run:
          name: Javadoc
          command: make javadoc

      # Save Javadoc results
      - store_artifacts:
          path: code/edgebridge/build/docs/javadoc

      - run:
          name: Assemble phone
          command: make assemble-phone

      - run:
          name: Assemble for Jitpack
          command: make ci-publish-maven-local-jitpack

      - run:
          name: Assemble App
          command: make assemble-app

      # Run unit tests and create code coverage report, with auto retry from run-tests command
      - android/run-tests:
          test-command: make unit-test-coverage

      - store_artifacts:
          path: code/edgebridge/build/reports/tests

      - store_test_results:
          path: code/edgebridge/build/test-results/testPhoneDebugUnitTest

      # Upload code coverage report to Codecov
      - codecov/upload:
          file: code/edgebridge/build/reports/coverage/test/phone/debug/report.xml
          flags: unit-tests
      
      - android/save-gradle-cache

      - android/save-build-cache

  functional-test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2024.01.1
    steps:
      - checkout

      - android/restore-build-cache

      # By default this command handles restoring and saving the Gradle cache
      - android/start-emulator-and-run-tests:
          # It should match the name seen in the "sdkmanager --list" output
          system-image: system-images;android-29;default;x86
          # The command to be run, while waiting for emulator startup
          post-emulator-launch-assemble-command: make assemble-phone
          # The test command
          test-command: make functional-test-coverage
      
      # Upload code coverage report to Codecov
      - codecov/upload:
          file: code/edgebridge/build/reports/coverage/androidTest/phone/connected/debug/report.xml
          flags: functional-tests

      - android/save-build-cache

      - store_artifacts:
          path: code/edgebridge/build/reports/androidTests

      - store_test_results:
          path: code/edgebridge/build/outputs/androidTest-results
          
    
