version: 2.1
orbs:
  # Use the circleci android orb version that supports OpenJDK17 required by AGP 8.2+
  android: circleci/android@2.4.0
  codecov: codecov/codecov@4.0.1

# Workflows orchestrate a set of jobs to be run;
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - validate-code
      - build-and-unit-test:
          requires:
            - validate-code
      - functional-test:
          requires:
            - validate-code
 
jobs:
  validate-code:
    docker:
      - image: cimg/android:2024.01-node
    steps:
      - checkout

      # - run:
      #     name: Check code format
      #     command: make checkformat
      
      # - run:
      #     name: Run lint
      #     command: make lint

  build-and-unit-test:
    docker:
      - image: cimg/android:2024.01
    steps:
      - checkout

      - run:
          name: Build java doc
          command: |
            make javadoc

      # Save Javadoc results
      - store_artifacts:
          path: code/edgebridge/build/docs/javadoc

      - run:
          name: Assemble phone
          command: make ci-assemble-phone

      - run:
          name: Build test app
          command: make assemble-app

      # - run:
      #     name: Run unit tests
      #     command: make unit-test

      - run:
          name: Run unit tests and create code coverage report
          command: |
            make unit-test-coverage

      - store_test_results:
          path: code/edgebridge/build/test-results/testPhoneDebugUnitTest

      # Upload code coverage report to Codecov
      - codecov/upload:
          file: code/edgebridge/build/reports/coverage/test/phone/debug/report.xml
          flags: unit-tests

  functional-test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2024.01.1
    steps:
      - checkout
      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86

      - android/start-emulator:
          avd-name: myavd
          no-window: true
          post-emulator-launch-assemble-command: ""
          restore-gradle-cache-prefix: v1a

      - run:
          name: Run Functional tests
          command: |
            make functional-test-coverage
      
      # Upload code coverage report to Codecov
      - codecov/upload:
          file: code/edgebridge/build/reports/coverage/androidTest/phone/connected/debug/report.xml
          flags: functional-tests

      - android/save-gradle-cache:
          cache-prefix: v1a

      - store_artifacts:
          path: code/edgebridge/build/reports/androidTests

      - store_test_results:
          path: code/edgebridge/build/outputs/androidTest-results
          
    
